apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-catalog-config
  labels:
    app: ms-catalog
data:
  ConnectionStrings__DefaultConnection: "User ID=api; Password=postgres123; Server=ms-catalog-db; Port=5432; Database=ms-catalog; IntegratedSecurity=true; Pooling=true "
  ConnectionStrings__RedisConfiguration: "ms-catalog-cache:6379"
  RabbitMQ__Hostname: "event-bus.localdev.me"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
