apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-catalog-config
  labels:
    app: ms-catalog
data:
  ConnectionStrings__DefaultConnection: "User ID=api; Password=postgres123; Server=ms-catalog-db; Port=5432; Database=ms-catalog; IntegratedSecurity=true; Pooling=true "
  ConnectionStrings__RedisConfiguration: "ms-catalog-redis:6379"
