apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-catalog
  labels:
    app: ms-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-catalog
  template:
    metadata:
      labels:
        app: ms-catalog
    spec:
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - envFrom:
            - configMapRef:
                name: ms-catalog-config
            - secretRef:
                name: ms-catalog-secret
          image: yasinkara/ms-catalog:latest
          name: ms-catalog
          ports:
            - containerPort: 5000
          resources: {}
      initContainers:
        - name: check-db-ready
          image: postgres:9.6.5
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h ms-catalog-db -p 5432; do echo waiting for database; sleep 2; done;",
            ]
      restartPolicy: Always
