apiVersion: v1
kind: Service
metadata:
  name: ms-catalog
  labels:
    app: ms-catalog
spec:
  type: ClusterIP
  ports:
    - name: "web"
      port: 80
      targetPort: 5000
  selector:
    app: ms-catalog
